version: "latest"
services:
  git-server:
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    restart: always
    ports:
      - "8080:90"
    volumes:
      - ./repos:/var/www/git
